version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Choose either one of the orbs below
    # welcome: circleci/welcome-orb@0.4.1
    aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
    # build:  # Choose any name, such as `build`
    #     # The primary container, where your job's commands will run
    #     docker:
    #       - image: 
    #     steps:
    #       - checkout # check out the code in the project directory
    #       - run: echo "hello world" # run the `echo` command
    # create_infrastructure:
    #     docker:
    #       - image: amazon/aws-cli
    #     steps:
    #       - checkout
    #       - run:
    #           name: Create CloudFormation Stack
    #           command: |
    #             aws cloudformation deploy \
    #             --template-file template.yml \
    #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
    #             --region us-east-1

    configure_infrastructure:
        docker:
          - image: python:3.9.16
        steps:
          - checkout
          - add_ssh_keys:
              fingerprints:
                - "bf:4e:12:af:90:cd:f1:fc:a0:81:46:1f:83:43:6a:06"
          - run:
              name: Install Ansible
              command: |
                apt-get update -y
                apt install ansible -y
                which ansible
          - run:
              name: Run Playbook and Configure server
              command: |
                ansible-playbook main-remote.yml -i inventory --private-key udacity.pem
# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        # - build
        # - create_infrastructure
        - configure_infrastructure